// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace WebApi.Models
{
    public partial class ProductionSystemContext : DbContext
    {
        public DbSet<TreeOfMfgPlants> TreeOfMfgPlants { get; set; }

        public ProductionSystemContext(DbContextOptions<ProductionSystemContext> options)
            : base(options)
        {

        }


    }
}